#server:
#  port: 88
#spring:
#  application:
#    name: gulimall-gateway
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#        namespace: public
#        group: dev
#    loadbalancer:
#      cache:
#        enabled: false
#    gateway:
#      routes:
#        - id: coupon
#          uri: http://localhost:7000
#          predicates:
#            - Path=/coupon/**
#        - id: member
#          uri: http://localhost:8000
#          predicates:
#            - Path=/member/**
